name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: api-current-time
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore ./CurrentTime.sln
        
      - name: Build
        run: dotnet build ./CurrentTime.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./CurrentTime.sln --configuration Release --no-build --property PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: ALT 
        uses: Azure/pipelines@v1
        with:
            azure-devops-project-url: 'https://dev.azure.com/oscastan/FEVP'
            azure-pipeline-name: 'FEVP'
            azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
            
